# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_telemetrydestination.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None
    namespace: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Auth(BaseModel):
    bearerTokenKey: constr(max_length=253) | None = None
    """
    The key in this sink's Secret holding the bearer token. Modelplane mounts it as a file and points the authenticator at it, so a rotated token is picked up without restarting the collector.
    """


class SecretRef(BaseModel):
    name: constr(max_length=253)
    """
    Name of the Secret, in modelplane-system on the control plane. Modelplane copies it to every cluster running a collector, so it doesn't have to exist on each of them already.
    """


class Sink(BaseModel):
    auth: Auth | None = None
    """
    Authentication Modelplane sets up for this sink, using a credential from `secretRef`. For another scheme, define an authenticator under spec.extensions and reference it from `config`.
    Set here, it wins: Modelplane applies it over an `auth` block in `config`, so a sink's credential cannot be quietly unpicked.
    """
    config: dict[str, Any] | None = None
    """
    The rest of the exporter's configuration, passed through as written: TLS, retries, queueing, compression, headers.
    Modelplane sets one default, for the exporters that flatten a series into labels: prometheus and prometheus_remote_write get resource_to_telemetry_conversion, or they would receive every series stripped of the cluster, deployment, engine and role it belongs to. Setting it here overrides that.
    """
    endpoint: constr(max_length=2048) | None = None
    """
    Where this sink writes. Leave it unset for an exporter that doesn't take an endpoint, such as kafka or debug, and configure it in `config` instead.
    Set here, it wins: Modelplane applies it over `config`, so a sink cannot be quietly redirected by the configuration passed through beside it.
    """
    name: constr(pattern=r'^[a-z0-9]([-a-z0-9]*[a-z0-9])?$', max_length=63)
    """
    This sink's name, unique within the destination. It names the collector's exporter instance, the authenticator Modelplane composes for it, and the directory its credential mounts at, so renaming one restarts the collector.
    """
    secretRef: SecretRef | None = None
    """
    A Secret holding this sink's credentials. Modelplane mounts each key as a file under /etc/modelplane/telemetry/<sink name>/ and sets it as an environment variable for ${env:KEY} references in `config`. All sinks share one environment, so where two Secrets have the same key, refer to the file.
    """
    type: constr(max_length=63)
    """
    The collector exporter to send with, by the name OpenTelemetry gives it: otlphttp, otlp, prometheus_remote_write, kafka, and every other one the collector provides.
    Not an enum: the collector already refuses to start on a name it doesn't have, so repeating the list here would only add a second place for it to go stale.
    """


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    extensions: dict[str, Any] | None = None
    """
    Collector extensions, passed through as written. Use it to define an authenticator that a sink's `config` references.
    An exporter needs a client authenticator - basicauth, oauth2client, sigv4auth, headers_setter. The oidc extension authenticates callers of a receiver, so it is not one of these.
    """
    sinks: list[Sink] = Field(..., max_length=16, min_length=1)
    """
    Where to send it. Every sink gets the whole stream, so two sinks is two copies of the fleet's metrics, billed twice.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """


class TelemetryDestination(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['TelemetryDestination'] | None = 'TelemetryDestination'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    Where the fleet's metrics go. Modelplane runs no collectors until a TelemetryDestination exists, and creating one turns on collection on every inference cluster.
    Several can exist. Their sinks are concatenated into one collector configuration, so adding a backend is a new object rather than an edit to one somebody else owns. A sink's name is the collector's name for its exporter, so it has to be unique across destinations.
    """
    status: Status | None = None


class TelemetryDestinationList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[TelemetryDestination]
    """
    List of telemetrydestinations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """