# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_telemetrydestination.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None
    namespace: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class SecretRef(BaseModel):
    name: constr(max_length=253)
    """
    Name of the Secret, in Modelplane's namespace.
    """


class Sink(BaseModel):
    config: dict[str, Any]
    """
    That exporter's own configuration, passed through unread. Modelplane does not model what an exporter is, so TLS, retry, queue and compression settings all work, and a sink keeps working when the collector gains a setting Modelplane has never heard of.
    """
    name: constr(pattern=r'^[a-z0-9]([-a-z0-9]*[a-z0-9])?$', max_length=63)
    """
    This sink's name, unique within the destination. It names the collector's exporter instance and the directory its credential mounts at, so renaming one restarts the collector.
    """
    secretRef: SecretRef | None = None
    """
    A Secret holding this sink's credential. Its keys reach the collector as environment variables, for config above referring to ${env:TOKEN}, and as files under /etc/modelplane/telemetry/<sink name>/, for an authenticator reading one from disk.
    Per sink rather than per destination, so two sinks with different credentials don't have to share one Secret and tell their keys apart by prefix. A file is refreshed in place where an environment variable is fixed for the life of the process, so an authenticator reading the file picks up a rotated credential without a restart.
    """
    type: constr(max_length=63)
    """
    The collector exporter to send with, by the name OpenTelemetry gives it: otlphttp, otlp, prometheusremotewrite, kafka, and every other one the collector provides.
    Not an enum, because enumerating them here would mean a Modelplane release for each exporter the collector gains, and the collector already refuses to start on a name it doesn't have.
    """


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    extensions: dict[str, Any] | None = None
    """
    The collector's extensions block, passed through unread, for the authenticator a sink references. Bearer token, basic auth, OIDC and SigV4 all work, because none of them is modelled here.
    """
    sinks: list[Sink] = Field(..., max_length=16, min_length=1)
    """
    Where to send it. Every sink gets the whole stream, so two sinks is two copies of the fleet's metrics, billed twice.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """


class TelemetryDestination(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['TelemetryDestination'] | None = 'TelemetryDestination'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    Where the fleet's telemetry goes. Modelplane composes no collectors until a TelemetryDestination exists: neither tier stores anything, so collecting with nowhere to export would spend GPU-cluster memory on samples nobody reads. Creating one turns collection on everywhere at once.
    There is no per-deployment opt-out. A ModelDeployment's author owns neither the destination nor its bill.
    """
    status: Status | None = None


class TelemetryDestinationList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[TelemetryDestination]
    """
    List of telemetrydestinations. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """