# generated by datamodel-codegen:
#   filename:  workdir/billing_nebius_upbound_io_v1beta1_pricingpolicy.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field

from .....k8s.apimachinery.pkg.apis.meta import v1 as v1_1


class V1(BaseModel):
    platform: str | None = None
    """
    Compute platform. Example: "gpu-h100-sxm".
    """


class ComputeInstanceSpec(BaseModel):
    v1: V1 | None = None


class MaxPriceV1(BaseModel):
    maxPrice: str | None = None
    """
    :

    Per-GPU hourly limit in USD, decimal string 3 digits precision. Example: "3.515".
    Must be within the allowed price range (OUT_OF_RANGE otherwise);
    a value below the current market price is accepted but blocks scheduling.
    Mutable only while `status.running_vm_count` is 0
    (FAILED_PRECONDITION otherwise); the policy reports STATE_UPDATING and
    blocks scheduling while the change is applied.
    """


class Pricing(BaseModel):
    maxPriceV1: MaxPriceV1 | None = None


class ForProvider(BaseModel):
    computeInstanceSpec: ComputeInstanceSpec | None = None
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    pricing: Pricing | None = None


class InitProvider(BaseModel):
    computeInstanceSpec: ComputeInstanceSpec | None = None
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    pricing: Pricing | None = None


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class ProviderConfigRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """
    namespace: str
    """
    Namespace of the secret.
    """


class Spec(BaseModel):
    deletionPolicy: Literal['Orphan', 'Delete'] | None = 'Delete'
    """
    DeletionPolicy specifies what will happen to the underlying external
    when this managed resource is deleted - either "Delete" or "Orphan" the
    external resource.
    This field is planned to be deprecated in favor of the ManagementPolicies
    field in a future release. Currently, both could be set independently and
    non-default values would be honored if the feature flag is enabled.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    """
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    This field is planned to replace the DeletionPolicy field in a future
    release. Currently, both could be set independently and non-default
    values would be honored if the feature flag is enabled. If both are
    custom, the DeletionPolicy field will be ignored.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class Status(BaseModel):
    currency: str | None = None
    """
    ISO 4217 currency code of max_price, e.g. "USD".
    """
    runningVmCount: float | None = None
    """
    :

    Number of VMs currently running under this policy. Nonzero blocks resource
    changes and deletion.
    """
    schedulingState: str | None = None
    """
    :

    Whether new VMs may currently start under this policy.

    #### Supported values

    Possible values:

    - `SCHEDULING_STATE_UNSPECIFIED`
    - `SCHEDULING_STATE_ALLOWED` - New VMs may start.
    - `SCHEDULING_STATE_BLOCKED`:
    The max_price limit is below the market price in force or below a market price
    that is being applied; VM creation succeeds once the price falls to it.
    """
    skuId: str | None = None
    """
    SKU resolved from the spec.
    """
    state: str | None = None
    """
    :

    #### Supported values

    Possible values:

    - `STATE_UNSPECIFIED`
    - `STATE_CREATING`:
    Not ready yet; a VM referencing the policy gets a retryable error.
    The state can last while a market price change is applied to the segment.

    - `STATE_ACTIVE` - Ready; whether VMs may start is `scheduling_state`.
    - `STATE_DELETING` - Being deleted; does not accept new VMs.
    - `STATE_UPDATING`:
    The bid is being changed; scheduling is blocked until the change lands.
    The state can last while a market price change is applied to the segment.
    """


class AtProvider(BaseModel):
    computeInstanceSpec: ComputeInstanceSpec | None = None
    createdAt: str | None = None
    """
    :

    Timestamp indicating when the resource was created.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """
    id: str | None = None
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    labelsAll: dict[str, str] | None = None
    """
    Effective labels sent to the API after merging provider `default_labels` with resource `labels`.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    pricing: Pricing | None = None
    resourceVersion: float | None = None
    """
    :

    Version of the resource for safe concurrent modifications and consistent reads.
    Positive and monotonically increases on each resource spec change (but *not* on each change of the
    resource's container(s) or status).
    Service allows zero value or current.
    """
    status: Status | None = None
    updatedAt: str | None = None
    """
    :

    Timestamp indicating when the resource was last updated.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class StatusModel(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class PricingPolicy(BaseModel):
    apiVersion: Literal['billing.nebius.upbound.io/v1beta1'] | None = (
        'billing.nebius.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['PricingPolicy'] | None = 'PricingPolicy'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1_1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    PricingPolicySpec defines the desired state of PricingPolicy
    """
    status: StatusModel | None = None
    """
    PricingPolicyStatus defines the observed state of PricingPolicy.
    """


class PricingPolicyList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[PricingPolicy]
    """
    List of pricingpolicies. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1_1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """