# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_metricmapping.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None
    namespace: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Label(BaseModel):
    from_: constr(pattern=r'^[a-zA-Z_][a-zA-Z0-9_]*$', max_length=63) | None = Field(
        None, alias='from'
    )
    """
    A label the component already emits. Modelplane copies its value into this label and removes the original.
    Naming the label itself keeps it: that is how `values` rewrites what a component writes without renaming the label.
    """
    name: constr(pattern=r'^[a-zA-Z_][a-zA-Z0-9_]*$', max_length=63)
    """
    The label to set.
    """
    value: constr(max_length=253) | None = None
    """
    A fixed value, the same on every series this mapping produces. This is what tells two folded metrics apart.
    """
    values: dict[str, constr(max_length=253)] | None = Field(None, max_length=32)
    """
    What each of that label's values becomes, for putting an engine's own vocabulary into Modelplane's. A value with no entry here is left as the component wrote it.
    """


class Metric(BaseModel):
    from_: constr(pattern=r'^[a-zA-Z_:][a-zA-Z0-9_:]*$', max_length=255) = Field(
        ..., alias='from'
    )
    """
    The metric's name as the component exposes it, matched exactly wherever it appears in the fleet.
    A histogram is named by its base name, without the _count, _sum or _bucket a Prometheus query would use: the collector holds it as one metric, and `part` is what reaches into it.
    """
    fromUnit: (
        Literal['Millijoules', 'Mebibytes', 'Milliseconds', 'Nanoseconds', 'Percent']
        | None
    ) = None
    """
    What the component measures this in, when that isn't the unit the name claims. Modelplane converts to the base unit: millijoules and milliseconds are divided by a thousand, nanoseconds by a billion, percent by a hundred, and mebibytes multiplied out to bytes. A histogram is converted whole - its sum, its bounds and its bucket boundaries - so its quantiles come out in the target unit too.
    Percent is for a component that counts a saturation from nought to a hundred where the name says a ratio. Check rather than assume: vLLM publishes kv_cache_usage_perc and the value is a fraction, so a name is no guide.
    """
    labels: list[Label] | None = Field(None, max_length=16)
    """
    Labels to set on this metric's series. To fold several metrics into one name, give each its own entry with the same `to` and a different fixed value, such as direction: input and direction: output on modelplane_tokens_total.
    """
    part: Literal['Count', 'Sum'] | None = None
    """
    Take a part of a histogram as a counter of its own, rather than the histogram itself. Count is how many observations it holds, which is a request count where the histogram measures request duration. Sum is their total.
    The extraction leaves the histogram alone, but the collector exports only what a mapping renames, so the histogram itself is dropped unless another mapping gives it a `modelplane_` name of its own. Write that second mapping to keep both.
    """
    to: constr(pattern=r'^modelplane_[a-z0-9_]*[a-z0-9]$', max_length=255)
    """
    The name to export the metric under. Only modelplane_* metrics leave a cluster, so a metric no mapping renames never leaves its cluster.
    Name it in base units - seconds, bytes, joules, a ratio from nought to one - because that is what `fromUnit` converts to.
    """


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    metrics: list[Metric] = Field(..., max_length=128, min_length=1)
    """
    The metrics to rename. Give two components' metrics the same name only if they measure the same thing, and histograms only if their buckets match too. A quantile across mismatched buckets is wrong.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    clusters: int | None = None
    """
    How many inference clusters apply this mapping.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """


class MetricMapping(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['MetricMapping'] | None = 'MetricMapping'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    How one component's metrics become part of the modelplane_* surface. Modelplane renders every MetricMapping into each inference cluster's collector, so a mapping is written once on the control plane and reaches the whole fleet.
    A mapping naming a component Modelplane already provides renames for is additive: its renames run after the built-in ones, on whatever those left behind. A metric a built-in already renamed no longer answers to the name it was emitted under, so a second mapping selecting on that name matches nothing and the built-in stands. Select on the `modelplane_` name instead to rename one of Modelplane's own.
    """
    status: Status | None = None


class MetricMappingList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[MetricMapping]
    """
    List of metricmappings. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """