# generated by datamodel-codegen:
#   filename:  workdir/modelplane_ai_v1alpha1_metricmapping.yaml

from __future__ import annotations

from typing import Literal

from pydantic import AwareDatetime, BaseModel, Field, constr

from ....io.k8s.apimachinery.pkg.apis.meta import v1


class CompositionRef(BaseModel):
    name: str


class CompositionRevisionRef(BaseModel):
    name: str


class CompositionRevisionSelector(BaseModel):
    matchLabels: dict[str, str]


class CompositionSelector(BaseModel):
    matchLabels: dict[str, str]


class ResourceRef(BaseModel):
    apiVersion: str
    kind: str
    name: str | None = None
    namespace: str | None = None


class Crossplane(BaseModel):
    compositionRef: CompositionRef | None = None
    compositionRevisionRef: CompositionRevisionRef | None = None
    compositionRevisionSelector: CompositionRevisionSelector | None = None
    compositionSelector: CompositionSelector | None = None
    compositionUpdatePolicy: Literal['Automatic', 'Manual'] | None = None
    resourceRefs: list[ResourceRef] | None = None


class Label(BaseModel):
    from_: constr(pattern=r'^[a-zA-Z_][a-zA-Z0-9_]*$', max_length=63) | None = Field(
        None, alias='from'
    )
    """
    A label the component already emits, carried onto the new name and dropped from the series under its old one.
    """
    name: constr(pattern=r'^[a-zA-Z_][a-zA-Z0-9_]*$', max_length=63)
    """
    The label to set.
    """
    value: constr(max_length=253) | None = None
    """
    A fixed value, the same on every series this mapping produces. This is what tells two folded metrics apart.
    """
    values: dict[str, constr(max_length=253)] | None = Field(None, max_length=32)
    """
    What each of that label's values becomes, for putting an engine's own vocabulary into Modelplane's. A value with no entry here is left as the component wrote it.
    Only meaningful alongside `from`.
    """


class Metric(BaseModel):
    acrossReplicas: Literal['Sum', 'Mean', 'Max']
    """
    How this metric combines over a deployment's replicas.
    Every pod publishes its own series, told apart by the replica it belongs to and the instance it was scraped from, and a query over a deployment combines them. This says which combination is the right one: Sum for anything counted - requests, tokens, joules, a queue's depth. Mean for a ratio, where summing reads two replicas at half capacity as one at full. Max for a saturation figure an alert fires on, where a mean hides the replica in trouble.
    Modelplane does not combine them in the collector. A scrape of one replica is one batch, so a collector that added them up would be adding readings taken at different moments, and two readings of one cumulative counter sum to twice the traffic that happened. The backend holds every replica's series and combines them at query time, where the arithmetic is right.
    Required, with no default, because the wrong combination is silent: a deployment reports a number that looks entirely plausible.
    """
    from_: constr(pattern=r'^[a-zA-Z_:][a-zA-Z0-9_:]*$', max_length=255) = Field(
        ..., alias='from'
    )
    """
    The metric's name as the component emits it, matched exactly. Nothing here declares which engine a deployment runs: a name that no component emits simply matches nothing.
    Held to the characters a metric name can contain. The name is matched inside the collector's own query language, so a quote here would end the comparison early and rename whatever the rest of the line matched.
    """
    fromUnit: (
        Literal['Millijoules', 'Mebibytes', 'Milliseconds', 'Nanoseconds', 'Percent']
        | None
    ) = None
    """
    What the component measures this in, when that isn't the unit the name claims. Modelplane converts to the base unit: millijoules and milliseconds are divided by a thousand, nanoseconds by a billion, percent by a hundred, and mebibytes multiplied out to bytes.
    Percent is for a component that counts a saturation from nought to a hundred where the name says a ratio. Check rather than assume: vLLM publishes kv_cache_usage_perc and the value is a fraction, so a name is no guide.
    Say it whenever the source disagrees with the target, even where the factor looks obvious. A name ending in _bytes that holds mebibytes is the kind of thing nobody notices until a capacity review, and stating the source unit is what makes the conversion happen at all.
    """
    labels: list[Label] | None = Field(None, max_length=16)
    """
    Labels to set on the series, for folding several metrics into one that a label tells apart - tokens in and out under one name with a direction, responses under one name with the reason they ended.
    Two mappings writing the same `to` with a different fixed value is how the fold is expressed: each renames its own source and stamps its own value.
    """
    part: Literal['Count', 'Sum'] | None = None
    """
    Take a part of a histogram as a counter of its own, rather than the histogram itself. Count is how many observations it holds, which is a request count where the histogram measures request duration. Sum is their total.
    The histogram carries on unchanged under its own name. This adds a series beside it.
    """
    to: constr(pattern=r'^modelplane_[a-z0-9_]*[a-z0-9]$', max_length=255)
    """
    What Modelplane calls it. Only modelplane_* leaves a cluster, so a metric with no name here is one nobody downstream can read.
    """


class Spec(BaseModel):
    crossplane: Crossplane | None = None
    """
    Configures how Crossplane will reconcile this composite resource
    """
    metrics: list[Metric] = Field(..., max_length=128, min_length=1)
    """
    The metrics this component emits, and what Modelplane calls them.
    Rename only where the measurements agree. Two engines' histograms sharing a name are worth less than nothing if their buckets disagree, because a quantile across them is wrong rather than approximate.
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    message: str | None = None
    observedGeneration: int | None = None
    reason: str
    status: str
    type: str


class Status(BaseModel):
    clusters: int | None = None
    """
    How many inference clusters have taken these statements.
    """
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """


class MetricMapping(BaseModel):
    apiVersion: Literal['modelplane.ai/v1alpha1'] | None = 'modelplane.ai/v1alpha1'
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['MetricMapping'] | None = 'MetricMapping'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    How one component's metrics become part of the modelplane_* surface. Modelplane renders every MetricMapping into each inference cluster's collector, so a mapping is written once on the control plane and reaches the whole fleet.
    A mapping naming a component Modelplane already provides renames for is additive: its renames run after the built-in ones, and a later rename of the same metric wins.
    """
    status: Status | None = None


class MetricMappingList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[MetricMapping]
    """
    List of metricmappings. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """