# generated by datamodel-codegen:
#   filename:  workdir/storage_nebius_m_upbound_io_v1beta1_inventory.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class DestinationBucketIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class DestinationBucketIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ParentIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class ParentIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    destinationBucketId: str | None = None
    """
    ID of the destination bucket.
    """
    destinationBucketIdRef: DestinationBucketIdRef | None = None
    """
    Reference to a Bucket in storage to populate destinationBucketId.
    """
    destinationBucketIdSelector: DestinationBucketIdSelector | None = None
    """
    Selector for a Bucket in storage to populate destinationBucketId.
    """
    destinationPrefix: str | None = None
    """
    Prefix under which bucket inventory will be stored in the destination bucket.
    """
    enabled: bool | None = None
    """
    Enable or disable inventory generation.
    """
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    noncurrentVersions: bool | None = None
    """
    Include noncurrent versions in inventory if set to true.
    """
    optionalFields: list[str] | None = None
    """
    :

    Optional fields to include in inventory.

    #### Supported values

    Possible values:

    - `OPTIONAL_FIELD_UNSPECIFIED`
    - `LAST_ACCESS` - Timestamp of the last access.
    - `CHECKSUM_ALGORITHMS` - Checksum algorithms used.
    - `INTELLIGENT_TIER` - Current intelligent tier (for Intelligent Storage Class).
    - `IS_MULTIPART_UPLOAD` - True for multipart uploads, false for simple objects.
    - `LIFECYCLE_EXPIRATION` - Timestamp of lifecycle expiration.
    - `TAGS` - Object tags.
    """
    outputFormat: str | None = None
    """
    :

    Inventory format.

    #### Supported values

    Possible values:

    - `OUTPUT_FORMAT_UNSPECIFIED`
    - `CSV_GZIP` - CSV compressed with GZIP.
    - `PARQUET_SNAPPY` - Parquet compressed with Snappy.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    parentIdRef: ParentIdRef | None = None
    """
    Reference to a Bucket in storage to populate parentId.
    """
    parentIdSelector: ParentIdSelector | None = None
    """
    Selector for a Bucket in storage to populate parentId.
    """
    schedule: str | None = None
    """
    :

    How often to generate the inventory.

    #### Supported values

    Possible values:

    - `SCHEDULE_UNSPECIFIED`
    - `DAILY` - Run once a day.
    - `WEEKLY` - Run once a week.
    """
    sourcePrefix: str | None = None
    """
    Prefix to filter objects in the source bucket.
    """


class InitProvider(BaseModel):
    destinationBucketId: str | None = None
    """
    ID of the destination bucket.
    """
    destinationBucketIdRef: DestinationBucketIdRef | None = None
    """
    Reference to a Bucket in storage to populate destinationBucketId.
    """
    destinationBucketIdSelector: DestinationBucketIdSelector | None = None
    """
    Selector for a Bucket in storage to populate destinationBucketId.
    """
    destinationPrefix: str | None = None
    """
    Prefix under which bucket inventory will be stored in the destination bucket.
    """
    enabled: bool | None = None
    """
    Enable or disable inventory generation.
    """
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    noncurrentVersions: bool | None = None
    """
    Include noncurrent versions in inventory if set to true.
    """
    optionalFields: list[str] | None = None
    """
    :

    Optional fields to include in inventory.

    #### Supported values

    Possible values:

    - `OPTIONAL_FIELD_UNSPECIFIED`
    - `LAST_ACCESS` - Timestamp of the last access.
    - `CHECKSUM_ALGORITHMS` - Checksum algorithms used.
    - `INTELLIGENT_TIER` - Current intelligent tier (for Intelligent Storage Class).
    - `IS_MULTIPART_UPLOAD` - True for multipart uploads, false for simple objects.
    - `LIFECYCLE_EXPIRATION` - Timestamp of lifecycle expiration.
    - `TAGS` - Object tags.
    """
    outputFormat: str | None = None
    """
    :

    Inventory format.

    #### Supported values

    Possible values:

    - `OUTPUT_FORMAT_UNSPECIFIED`
    - `CSV_GZIP` - CSV compressed with GZIP.
    - `PARQUET_SNAPPY` - Parquet compressed with Snappy.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    parentIdRef: ParentIdRef | None = None
    """
    Reference to a Bucket in storage to populate parentId.
    """
    parentIdSelector: ParentIdSelector | None = None
    """
    Selector for a Bucket in storage to populate parentId.
    """
    schedule: str | None = None
    """
    :

    How often to generate the inventory.

    #### Supported values

    Possible values:

    - `SCHEDULE_UNSPECIFIED`
    - `DAILY` - Run once a day.
    - `WEEKLY` - Run once a week.
    """
    sourcePrefix: str | None = None
    """
    Prefix to filter objects in the source bucket.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class Status(BaseModel):
    errorCode: str | None = None
    """
    :

    Error code, if the last run was not successful, otherwise NO_ERROR.

    #### Supported values

    Possible values:

    - `NO_ERROR` - No error.
    - `DESTINATION_BUCKET_NOT_FOUND` - Destination bucket not found.
    - `PERMISSION_DENIED` - Permission denied: you don't have permission to the destination bucket.
    - `INVALID_INTENT` - Intent is invalid, does not exist or expired.
    - `QUOTA_EXCEEDED` - Quota exceeded in destination.
    """
    lastSuccess: str | None = None
    """
    :

    Timestamp of the last successful run.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """


class AtProvider(BaseModel):
    createdAt: str | None = None
    """
    :

    Timestamp indicating when the resource was created.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """
    destinationBucketId: str | None = None
    """
    ID of the destination bucket.
    """
    destinationPrefix: str | None = None
    """
    Prefix under which bucket inventory will be stored in the destination bucket.
    """
    enabled: bool | None = None
    """
    Enable or disable inventory generation.
    """
    id: str | None = None
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    labelsAll: dict[str, str] | None = None
    """
    Effective labels sent to the API after merging provider `default_labels` with resource `labels`.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    noncurrentVersions: bool | None = None
    """
    Include noncurrent versions in inventory if set to true.
    """
    optionalFields: list[str] | None = None
    """
    :

    Optional fields to include in inventory.

    #### Supported values

    Possible values:

    - `OPTIONAL_FIELD_UNSPECIFIED`
    - `LAST_ACCESS` - Timestamp of the last access.
    - `CHECKSUM_ALGORITHMS` - Checksum algorithms used.
    - `INTELLIGENT_TIER` - Current intelligent tier (for Intelligent Storage Class).
    - `IS_MULTIPART_UPLOAD` - True for multipart uploads, false for simple objects.
    - `LIFECYCLE_EXPIRATION` - Timestamp of lifecycle expiration.
    - `TAGS` - Object tags.
    """
    outputFormat: str | None = None
    """
    :

    Inventory format.

    #### Supported values

    Possible values:

    - `OUTPUT_FORMAT_UNSPECIFIED`
    - `CSV_GZIP` - CSV compressed with GZIP.
    - `PARQUET_SNAPPY` - Parquet compressed with Snappy.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    resourceVersion: float | None = None
    """
    :

    Version of the resource for safe concurrent modifications and consistent reads.
    Positive and monotonically increases on each resource spec change (but *not* on each change of the
    resource's container(s) or status).
    Service allows zero value or current.
    """
    schedule: str | None = None
    """
    :

    How often to generate the inventory.

    #### Supported values

    Possible values:

    - `SCHEDULE_UNSPECIFIED`
    - `DAILY` - Run once a day.
    - `WEEKLY` - Run once a week.
    """
    sourcePrefix: str | None = None
    """
    Prefix to filter objects in the source bucket.
    """
    status: Status | None = None
    updatedAt: str | None = None
    """
    :

    Timestamp indicating when the resource was last updated.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class StatusModel(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class Inventory(BaseModel):
    apiVersion: Literal['storage.nebius.m.upbound.io/v1beta1'] | None = (
        'storage.nebius.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['Inventory'] | None = 'Inventory'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    InventorySpec defines the desired state of Inventory
    """
    status: StatusModel | None = None
    """
    InventoryStatus defines the observed state of Inventory.
    """


class InventoryList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[Inventory]
    """
    List of inventories. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """