# generated by datamodel-codegen:
#   filename:  workdir/compute_nebius_m_upbound_io_v1beta1_disksnapshot.yaml

from __future__ import annotations

from typing import Any, Literal

from pydantic import AwareDatetime, BaseModel, Field

from ......k8s.apimachinery.pkg.apis.meta import v1


class Policy(BaseModel):
    resolution: Literal['Required', 'Optional'] | None = 'Required'
    """
    Resolution specifies whether resolution of this reference is required.
    The default is 'Required', which means the reconcile will fail if the
    reference cannot be resolved. 'Optional' means this reference will be
    a no-op if it cannot be resolved.
    """
    resolve: Literal['Always', 'IfNotPresent'] | None = None
    """
    Resolve specifies when this reference should be resolved. The default
    is 'IfNotPresent', which will attempt to resolve the reference only when
    the corresponding field is not present. Use 'Always' to resolve the
    reference on every reconcile.
    """


class SourceDiskIdRef(BaseModel):
    name: str
    """
    Name of the referenced object.
    """
    namespace: str | None = None
    """
    Namespace of the referenced object
    """
    policy: Policy | None = None
    """
    Policies for referencing.
    """


class SourceDiskIdSelector(BaseModel):
    matchControllerRef: bool | None = None
    """
    MatchControllerRef ensures an object with the same controller reference
    as the selecting object is selected.
    """
    matchLabels: dict[str, str] | None = None
    """
    MatchLabels ensures an object with matching labels is selected.
    """
    namespace: str | None = None
    """
    Namespace for the selector
    """
    policy: Policy | None = None
    """
    Policies for selection.
    """


class ForProvider(BaseModel):
    description: str | None = None
    """
    Arbitrary information about this snapshot provided by user.
    """
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    sourceDiskId: str | None = None
    """
    Identifier of the source disk. May become stale if the disk is deleted.
    """
    sourceDiskIdRef: SourceDiskIdRef | None = None
    """
    Reference to a Disk in compute to populate sourceDiskId.
    """
    sourceDiskIdSelector: SourceDiskIdSelector | None = None
    """
    Selector for a Disk in compute to populate sourceDiskId.
    """


class InitProvider(BaseModel):
    description: str | None = None
    """
    Arbitrary information about this snapshot provided by user.
    """
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    sourceDiskId: str | None = None
    """
    Identifier of the source disk. May become stale if the disk is deleted.
    """
    sourceDiskIdRef: SourceDiskIdRef | None = None
    """
    Reference to a Disk in compute to populate sourceDiskId.
    """
    sourceDiskIdSelector: SourceDiskIdSelector | None = None
    """
    Selector for a Disk in compute to populate sourceDiskId.
    """


class ProviderConfigRef(BaseModel):
    kind: str
    """
    Kind of the referenced object.
    """
    name: str
    """
    Name of the referenced object.
    """


class WriteConnectionSecretToRef(BaseModel):
    name: str
    """
    Name of the secret.
    """


class Spec(BaseModel):
    forProvider: ForProvider
    initProvider: InitProvider | None = None
    """
    THIS IS A BETA FIELD. It will be honored
    unless the Management Policies feature flag is disabled.
    InitProvider holds the same fields as ForProvider, with the exception
    of Identifier and other resource reference fields. The fields that are
    in InitProvider are merged into ForProvider when the resource is created.
    The same fields are also added to the terraform ignore_changes hook, to
    avoid updating them after creation. This is useful for fields that are
    required on creation, but we do not desire to update them after creation,
    for example because of an external controller is managing them, like an
    autoscaler.
    """
    managementPolicies: (
        list[Literal['Observe', 'Create', 'Update', 'Delete', 'LateInitialize', '*']]
        | None
    ) = ['*']
    """
    THIS IS A BETA FIELD. It is on by default but can be opted out
    through a Crossplane feature flag.
    ManagementPolicies specify the array of actions Crossplane is allowed to
    take on the managed and external resources.
    See the design doc for more information: https://github.com/crossplane/crossplane/blob/499895a25d1a1a0ba1604944ef98ac7a1a71f197/design/design-doc-observe-only-resources.md?plain=1#L223
    and this one: https://github.com/crossplane/crossplane/blob/444267e84783136daa93568b364a5f01228cacbe/design/one-pager-ignore-changes.md
    """
    providerConfigRef: ProviderConfigRef | None = Field(
        {'kind': 'ClusterProviderConfig', 'name': 'default'}, validate_default=True
    )
    """
    ProviderConfigReference specifies how the provider that will be used to
    create, observe, update, and delete this managed resource should be
    configured.
    """
    writeConnectionSecretToRef: WriteConnectionSecretToRef | None = None
    """
    WriteConnectionSecretToReference specifies the namespace and name of a
    Secret to which any connection details for this managed resource should
    be written. Connection details frequently include the endpoint, username,
    and password required to connect to the managed resource.
    """


class LockState(BaseModel):
    disks: list[str] | None = None
    """
    :

    The snapshot is locked for deletion while disk is being created from this snapshot.
    Here is the list of these disks.
    """


class Status(BaseModel):
    contentSizeBytes: float | None = None
    """
    :

    Logical size of the snapshot content.
    This is the size of a disk that would be created from this snapshot.
    """
    lockState: LockState | None = None
    sourceCpuArchitecture: str | None = None
    """
    :

    CPU architecture associated with the source disk.
    Not set if the architecture is unknown.

    #### Supported values

    Right now UNDEFINED is an alias for AMD64, but that might change in the future
    Possible values:

    - `UNDEFINED`
    - `AMD64`
    - `ARM64`
    """
    state: str | None = None
    """
    :

    #### Supported values

    All possible states for DiskSnapshot resource
    Possible values:

    - `UNSPECIFIED`
    - `CREATING`
    - `READY`
    - `DELETING`
    - `ERROR`
    """
    storageSizeBytes: float | None = None
    """
    :

    Physical storage used by this snapshot in the snapshot backend.
    This value is used for billing and quota and may change over time as the snapshot chain evolves
    (e.g., when earlier snapshots are deleted and data gets re-attributed).
    Currently is equal to content_size_bytes, as incremental snapshots are not supported yet.
    """


class AtProvider(BaseModel):
    createdAt: str | None = None
    """
    :

    Timestamp indicating when the resource was created.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """
    description: str | None = None
    """
    Arbitrary information about this snapshot provided by user.
    """
    id: str | None = None
    labels: dict[str, str] | None = None
    """
    Labels associated with the resource.
    """
    labelsAll: dict[str, str] | None = None
    """
    Effective labels sent to the API after merging provider `default_labels` with resource `labels`.
    """
    metadata: dict[str, Any] | None = None
    name: str | None = None
    """
    Human readable name for the resource.
    """
    parentId: str | None = None
    """
    Identifier of the parent resource to which the resource belongs.
    """
    resourceVersion: float | None = None
    """
    :

    Version of the resource for safe concurrent modifications and consistent reads.
    Positive and monotonically increases on each resource spec change (but *not* on each change of the
    resource's container(s) or status).
    Service allows zero value or current.
    """
    sourceDiskId: str | None = None
    """
    Identifier of the source disk. May become stale if the disk is deleted.
    """
    status: Status | None = None
    updatedAt: str | None = None
    """
    :

    Timestamp indicating when the resource was last updated.

    A string representing a timestamp in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format: `YYYY-MM-DDTHH:MM:SSZ` or `YYYY-MM-DDTHH:MM:SS.SSS±HH:MM`
    """


class Condition(BaseModel):
    lastTransitionTime: AwareDatetime
    """
    LastTransitionTime is the last time this condition transitioned from one
    status to another.
    """
    message: str | None = None
    """
    A Message containing details about this condition's last transition from
    one status to another, if any.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration represents the .metadata.generation that the condition was set based upon.
    For instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date
    with respect to the current state of the instance.
    """
    reason: str
    """
    A Reason for this condition's last transition from one status to another.
    """
    status: str
    """
    Status of this condition; is it currently True, False, or Unknown?
    """
    type: str
    """
    Type of this condition. At most one of each condition type may apply to
    a resource at any point in time.
    """


class StatusModel(BaseModel):
    atProvider: AtProvider | None = None
    conditions: list[Condition] | None = None
    """
    Conditions of the resource.
    """
    lastHandledReconcileAt: str | None = None
    """
    LastHandledReconcileAt holds the value of the most recent
    reconcile-requested-at annotation token that the controller has
    processed. Users can compare this to the annotation to determine
    whether a reconcile request has been handled.
    """
    observedGeneration: int | None = None
    """
    ObservedGeneration is the latest metadata.generation
    which resulted in either a ready state, or stalled due to error
    it can not recover from without human intervention.
    """


class DiskSnapshot(BaseModel):
    apiVersion: Literal['compute.nebius.m.upbound.io/v1beta1'] | None = (
        'compute.nebius.m.upbound.io/v1beta1'
    )
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    kind: Literal['DiskSnapshot'] | None = 'DiskSnapshot'
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ObjectMeta | None = None
    """
    Standard object's metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata
    """
    spec: Spec
    """
    DiskSnapshotSpec defines the desired state of DiskSnapshot
    """
    status: StatusModel | None = None
    """
    DiskSnapshotStatus defines the observed state of DiskSnapshot.
    """


class DiskSnapshotList(BaseModel):
    apiVersion: str | None = None
    """
    APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
    """
    items: list[DiskSnapshot]
    """
    List of disksnapshots. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md
    """
    kind: str | None = None
    """
    Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """
    metadata: v1.ListMeta | None = None
    """
    Standard list metadata. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
    """